wso2/identity-organization-management-core

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Add recent changes made to org mgt service module

---

.github/workflows/pr-builder.yml
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

> Add PR builder for the project and fixed checkstyle issues.

Add PR builder

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

> $subject
- https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/77

Fix for NPE when the user realm is not initilized

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

Fix change in get authenticated user name method

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
pom.xml

part of fix Fix https://github.com/wso2/product-is/issues/14001

Store tenant creator id in realm when creation tenants by organization creation

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/Organization.java

$Subject
Part of fix: https://github.com/wso2-enterprise/asgardeo-product/issues/12166

Add capability to define organization creator id,name and mail from another service

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

Reverts wso2-extensions/identity-organization-management-core#9

Revert "Fix for NPE when the user realm is not initilized"

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java

Add a service to get the depth of the organization in the hierarchy

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java

Use organization id and tenant domain as separate params to create tenants

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

Improve get user id to support federated users

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

This PR adds new error messages used in application sharing flows.

Add new error messages

---

components/org.wso2.carbon.identity.organization.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementServiceComponent.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/OrganizationManagementConfigBuilder.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/OrganizationManagementConfigUtil.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java
pom.xml

The new config file is introduced as "organization-mgt.xml"
This code change contains the file reading logic and a util method named " useOrganizationRolesForValidation" to do role validation based on the config in the organization-mgt.xml file

Add logic to read organization-mgt.xml and util method useOrganizationRolesForValidation

---

components/org.wso2.carbon.identity.organization.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java

Improve user resolve from residence organization to validate the domain qualifier

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java

$Subject Otherwise PUT requests get failed if the org name is not changed in the request.

Validate name uniqueness among siblings only if the update request has different name compared to the current name

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Add invalid filter error msg for org role patch remove operation

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Update error message for invalid filter with organization role patch

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementDataHolder.java

Address review comments

---

components/org.wso2.carbon.identity.organization.management.service/pom.xml
features/org.wso2.carbon.identity.organization.management.core.server.feature/pom.xml
pom.xml

Update pom to major version 2.0.0 for IPK

Update pom to Major Development Version

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java

Update core service to interchange tenant and org uuids

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java

Fix for user resolving from resident organization when user is deleted

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

$subject
Depends on
- https://github.com/wso2-enterprise/identity-org-mgt-connector/pull/166

Add a util method to check if an organization supports organization qualified paths

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

This PR addresses the error message issues mentioned in the following comment.
- https://github.com/wso2-extensions/identity-organization-management-core/pull/22/files#r1060495052
- https://github.com/wso2-extensions/identity-organization-management-core/pull/22/files#r1060498057

Improve error messages related to application sharing

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Add error codes related to shared app role creation and deletion errors

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Add user role deletion error code

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

> Adding and updating OrganizationManagementConstants.ErrorMessages for tenant deletion to include formattable messages to include custom data.

Adding and updating Tenant Deletion Error Messages

---

components/org.wso2.carbon.identity.organization.management.service/pom.xml
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/FilterQueryBuilder.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImplTest.java
pom.xml

> Address reviews on https://github.com/wso2-extensions/identity-organization-management-core/pull/1

Address PR reviews

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationGroupResidentResolverService.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationGroupResidentResolverServiceImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementServiceComponent.java

> $Subject
> Identify the resident org id of a group in a sub-org role.

Add support methods to resolve group resident organization ID.

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Add error code for blocking shared application not to share again

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

> Adding error message to restrict application creation.
- https://github.com/wso2-extensions/identity-organization-management/pull/218

Add error message for restricting application creation

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/CacheBackedOrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java

> Need to get the depth between given two organizations. The organizations should be in the same branch to define the depth. The first and second org can be child or parent alternatively, but the relative depth should be return.

Add new service to fetch the relative organization depth between two organizations

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

> Add OrganizationManagementConstants.ERROR_CODE_ERROR_WHILE_INITIALIZING_SUB_ORGANIZATION_TENANT_DELETION_HANDLER

Add new error message

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/CacheBackedOrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java

Introduce getting parent organization id from child organization id

---

components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java

> $subject
> https://github.com/wso2/identity-organization-management-core/pull/78

Add test case for parent organization extraction

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

$subject
Fixes: https://github.com/wso2/product-is/issues/16687

Add check used db type is mysql util function.

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Issue: https://github.com/wso2/product-is/issues/16379

Add error constants related to org discovery management

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/exception/OrganizationManagementException.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementDataHolder.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementServiceComponent.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

> Adding util methods to check a tenant is an organization by tenant id or tenant domain
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the …

Adding util methods to check a tenant is an organization by tenant id or tenant domain

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/OrganizationManagementUtil.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

- Update `isOrganization` util method to handle the super tenant scenario.
- Refactor util method to `OrganizationManagementUtil` class.

Update isOrganization util method

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java

> $subject
- https://github.com/wso2/product-is/issues/17031

Allow organization creation only from immediate parent organization

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java

Improve parent organization validation check

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java

Skip organization role check for the b2b enabled tenants

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/CacheBackedOrganizationManagementDAO.java

During the tenant creation there is a change tenant domain getting added as a null to the cache.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to …

Avoid null getting added as tenant domain.

---

features/org.wso2.carbon.identity.organization.management.core.server.feature/resources/organization-mgt.xml
features/org.wso2.carbon.identity.organization.management.core.server.feature/resources/organization-mgt.xml.j2

Template self organization creation configs to the organization-mgt.xml files

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/CacheBackedOrganizationManagementDAO.java

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Fix null pointer while adding to cache.

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

> $subject
- https://github.com/wso2/product-is/issues/17606

Introduce new thread local property

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Add error code for blocking shared user update

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Reverts wso2/identity-organization-management-core#116

Revert "Add new error constants related to org discovery"

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java

- $subject
https://github.com/wso2/product-is/issues/18210

Fix queries to work with oracle DBs

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java

> Handle post add organization errors
- https://github.com/wso2/product-is/issues/18557
> If any erros occur in post add organization listners,  rollback the created organization.

Handle post add organization errors

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java

Issue https://github.com/wso2/product-is/issues/18808

Validate org owner information before org creation

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Issue https://github.com/wso2/product-is/issues/19280

Add error message related to revoking tokens of shared application

---

components/org.wso2.carbon.identity.organization.management.service/pom.xml
features/org.wso2.carbon.identity.organization.management.core.server.feature/pom.xml
pom.xml

$Subject
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …

Changing snapshot version for next release version

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

-  $subject
- Fix the issue of unable to create organization under a suborganization

Fix the sub org creation issue

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java

Improve sub org retrieving logic
Related issue:
- https://github.com/wso2-enterprise/asgardeo-product/issues/23309

Improve suborg retrieving logic

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/exception/NotImplementedException.java

Implement `NotImplementedException` for Organization Management

---

.github/workflows/pr-builder.yml
codecov.yml
pom.xml

Add codecov configuration

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java

Use prepared statements to set values within the IN clause of SQL query
The same approach used in: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1603

Use prepared statements to set values within the IN clause of SQL query

---

.github/workflows/pr-builder.yml

Update codecov action version

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

- $Subject
- https://github.com/wso2/product-is/issues/20953

Add Error Enum for Validating "login_hint" Attribute

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java

&subject
Fixes: https://github.com/wso2/product-is/issues/21602

Remove extra semicolon in Oracle query for retrieving organization meta attributes

---

components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
pom.xml

$subject
Related issue: https://github.com/wso2/product-is/issues/21200
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …

Upgrade carbon multitenancy version to 4.11.30

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

Add error constants for email domain validation handler.

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/cache/OrganizationIdCacheKey.java

Fix NPE issue in cachekey

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImplTest.java

$subject
This would retain the backward compatibility.

Set domain name as organization handle during organization creation

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
$subject
Related issues: https://github.com/wso2/product-is/issues/23526

Pass tenant-domain instead of organization-id when getting tenant-id for sub organizations

---

pom.xml

$subject
- https://github.com/wso2-extensions/identity-organization-management/pull/510

Bump org.wso2.identity.organization.mgt.imp.pkg.version.range

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

$subject
- https://github.com/wso2/carbon-identity-framework/pull/6641
- https://github.com/wso2/product-is/issues/23903

Add async operation status error codes.

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java

$subject
- https://github.com/wso2/identity-organization-management-core/pull/180
- https://github.com/wso2/product-is/issues/23903

Update async operation status error codes.

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/CacheBackedOrganizationManagementDAO.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/OrganizationNode.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImplTest.java

$subject
- https://github.com/wso2/product-is/issues/21100

Add support to get org as graph

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementServiceComponent.java

Remove unnecessary debug log checks

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java

To update the accessing organization.
Related PRs:
- https://github.com/wso2/identity-api-server/pull/907
Related issues: 
- https://github.com/wso2/product-is/issues/23526

Introducing Organization Management /self API Service

---

components/org.wso2.carbon.identity.organization.management.service/pom.xml
features/org.wso2.carbon.identity.organization.management.core.server.feature/pom.xml
pom.xml

Add the `next` suffix to the POM versions.
- https://github.com/wso2/product-is/issues/24775

[IS 7.2.0 POST ALPHA] Update `next` branch versions

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/BasicOrganization.java

Adding the organization version information to the `api/users/v1/me/organizations` response.

Add version to authorized organizations response

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/BasicOrganization.java

Sending the following pr to the next branch
- https://github.com/wso2/identity-organization-management-core/pull/202

[Next] Add version to authorized organizations response.

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

This pull request improves error handling in organization version checks when organizations are missing or deleted. The changes ensure that the system gracefully handles cases where an organization is not found, preventing unnecessary exceptions and providing clearer logic for feature inheritance checks.
- https://github.com/wso2/product-is/issues/25480

Improve error handling during inheritance enabled checks based on organization version.

---

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java

Sending the below fix to the next branch 
- https://github.com/wso2/identity-organization-management-core/pull/204

[Next] Improve error handling during inheritance enabled checks based on organization version
