wso2/identity-organization-management-core

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
The sub organizations can be managed by immediate parent organization by the enhanced organization access privileges https://github.com/wso2-extensions/identity-organization-management/pull/143. But that is relaxed to allow any parent organization to update/delete organization resources.
Also the organization view permission is further relaxed to allow access from the same organization as the organization meta data like description, name need to be requested from the same organization.
=> Allow organization resource update by any parent organization and view organization by same organization

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java
> The authenticated username is not set in the carbon context for cross tenant flows. When the tenant creation as a part of organization creation, the tenant admin is set as the organization creator. The organization creator can resides in different tenant and request can be initiated from a sub organization hence the tenant admin is not set properly as the authenticated username is null in the carbon context.
- https://github.com/wso2-enterprise/identity-org-mgt-connector/issues/76
=> Retrieve authenticated username when cross tenant flows.

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementDataHolder.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementServiceComponent.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/listener/OrganizationManagerListener.java, components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
> Since this component sits higher than the carbon-identity-framework component in the dependency hierarchy, there is no way to fire events. This PR add a listener so that we can implement the listener in lower level of the dependency hierarchy and fire events.
=> Add initial event firing mechanism

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java
>  The tenants created for Asgardeo organizations consist of different user realm compared to the super tenant. This fix tries to assume all the tenants have the super tenant user realm. This behaviour was there previously also as the datasource being static variable and assigned once, the first request from super tenant will set the datasource with respect to the user realm of the super tenant.
Changes done in the below PRs can be reverted by this.
- https://github.com/wso2-extensions/identity-organization-management-core/pull/9
- https://github.com/wso2-extensions/identity-organization-management/pull/152
=> Fix for datasource not populating properly

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/TenantTypeOrganization.java
- If the organization is tenant-type, it creates an underlying tenant.
- That tenant's domain name will become the organization id.
- But there can be reasons to change the tenant domain name except for the organization id.
- So this change gives the capability to change the tenant domain via the "PRE_ADD_ORGANIZATION" event
=> Give support to change tenant domain of underlying tenant of an organization instead of the organization id

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverService.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java
> Get the organization hierarchy from the currently accessed organization to the user resident organization.
> Properly resolve the organization hierarchy.
> Introduced a new service called `resolveResidentOrganizationHierarchy` to get the organization hierarchy as a list of organizations. The list is sorted as higher-level organizations are at the top.
=> Added a service to resolve the users' organization hierarchy until resident organization.

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java
> While searching user by traversing over the organization hierarchy, once the user found, check the user has at least one organization management permission assigned for the particular organization the user was found. But in the organization hierarchy top level orgs or either 1st level orgs might not have organization roles and hence though user found, the user resolution logic fails.
- https://github.com/wso2-extensions/identity-organization-management-core/pull/24
=> Improvement for resolve user from resident organization when the organization support carbon roles

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
> With this fix organizations with same name can't be created as immediate child organizations under a particular parent organization.
=> Restrict unique organization name for immediate child organizations under the parent organization

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java
>  The user resolve from resident organization should be improved to consider the user store managers while trying resolving users at the each level of the ancestor organizations. As a workaround, traverse through the all the ancestor orgs and conclude the resolved user at the end with respect to the order of base organization to the super organization.
=> Workaround for user resolve from residence organization issue

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/model/FilterQueryBuilder.java
- Fix setting timestamp type attribute (related to `UM_CREATED_TIME` and `UM_LAST_MODIFIED` fields) in database query when listing orgainzations.
- Add client exceptions for incorrect timestamp format passed for timestamp related filters and related unsupported operations when listing organizations.
=> Fix setting database timestamp attributes in filter considering proper datatype

components/org.wso2.carbon.identity.organization.management.service/pom.xml, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java
> The custom local user store manager implementations could have some custom implementations to find the user by the username, only from the primary user store when the username is not domain qualified. In these cases, the `resolveUserFromResidentOrganization` method should be robust to check the user in the secondary user store also.
=> Check user in secondary user store when the user store manager do not check the user in secondary store by default

components/org.wso2.carbon.identity.organization.management.service/pom.xml
> As a fix for the issue of when mocking the static methods of the Organization utils class, the test cases fails with class not found exception for the tenant management service. Having the provided scope will not cause for transitive dependencies and could resolve the class not found issues of the dependent components when mocking these classes.
=> Change tenant mgt dependency scope to provided

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/exception/NotImplementedException.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/listener/OrganizationManagerListener.java
> $Subject
> Add organization depth in hierarchy as a parameter to postDeleteOrganization function which can then pass it to POST_DELETE_ORGANIZATION event to be used in the sub organization tenant deletion process. 
> https://github.com/wso2-extensions/identity-organization-management/pull/194
=> Add organizationDepthInHierarchy parameter to OrganizationManagerListener.postDeleteOrganization function

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
> Updating OrganizationManagementConstants.ErrorMessages introduced for tenant deletion for the error codes to be continuous, after the deletion of the ErrorMessage with error code 65100
=> Update OrganizationManagementConstants.ErrorMessages for tenant deletion

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverService.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
> Add method to retrieve a user when the resident organization is known. This is a helping service method for implementations in https://github.com/wso2-extensions/identity-organization-management/pull/200
- https://github.com/wso2-enterprise/asgardeo-product/issues/15292
=> Add method to retrieve a user when the resident organization is known.

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagementInitializeImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/internal/OrganizationManagementServiceComponent.java, features/org.wso2.carbon.identity.organization.management.core.server.feature/resources/organization-mgt.xml, features/org.wso2.carbon.identity.organization.management.core.server.feature/resources/organization-mgt.xml.j2
> Enable the B2B feature by default. If B2B feature needs to be disabled add the below configuration.
```
[organization_management]
enable = false
```
- https://github.com/wso2/product-is/issues/16359
=> Add config to enable B2B feature by default

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
Issue: https://github.com/wso2/product-is/issues/16379
=> Add error constants related to adding organization discovery attribute

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
> When updating the organizations, if the organization status is "ACTIVE", the respective tenant will be activated. In order to load the tenant, relying on organization-id is incorrect. The organization-id should be converted to tenant-domain first of all.
=> Fix Tenant status update issue.

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java
> This fixes the unnecessary requestInvokingOrganizationId null check which causes issues in sub-organisation CRUD operations in tenant-qualified paths. With the following PR [1] organization ID will be returned even if it is a tenanted path as opposed to earlier functionality. If the organization ID couldn't be retrieved, a RuntimeException will be thrown. 
- [1] https://github.com/wso2/identity-organization-management-core/pull/103
=> Remove unnecessary requestInvokingOrganizationId null check in sub org handling

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationUserResidentResolverServiceImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java, pom.xml
> $subject
- https://github.com/wso2/product-is/issues/17520
This PR contains two efforts
- Remove the check for permissions of user against organization when resolving the user from the hierarchy. 
- Improve the user ID and user name resolving utils.
=> Remove the deprecated organization permission check when resolving the user from the organization hierarchy.

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java
>  The service URL resource links can be build at the controller layer (api-server repo). Hence the service URL building logics in the service layer methods can be removed.
- https://github.com/wso2/product-is/issues/17606
=> Remove the service URL builds at organization core level

components/org.wso2.carbon.identity.organization.management.service/pom.xml, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java, pom.xml
- Creating organization self service application related system user only when legacy Authorization runtime is enabled.
- https://github.com/wso2/product-is/issues/17693
=> Add check to create the self-service user for legacy authz runtime

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java
> With this PR https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/254 the correct username is set in the carbon context at the authentication valve level. Hence these type of logics are no more required.
- https://github.com/wso2/product-is/issues/17744
- https://github.com/wso2-extensions/identity-carbon-auth-rest/pull/254
=> Remove the obsolete logic of resolving the authenticated username of organization SSO users

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java
> GET_CHILD_ORGANIZATIONS query fails with ORA-00933: SQL command not properly ended
This is due to tailing semicolon in the query
> * https://github.com/wso2/product-is/issues/17974
=> Oracle db tailing semicolon issue fixed

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/filter/FilterTreeBuilder.java
- https://github.com/wso2/product-is/issues/18963
Fixing the bug where the organization names created with exclamation mark `!` cannot be edited in the console UI. By adding it to the list of enabled characters.
=> Allowing exclamation mark to be used in organization name

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationGroupResidentResolverServiceImpl.java
This will avoid the execution of the rest of the logic if the tenant domain is resolved as the super tenant. Super tenant is the last item of the ancestorOrganizationIds and from this changes, we are removing the super tenant when the sub org start level is above 1.
=> Add condition to avoid logic execution for super tenant after getting the ancestorOrganizationIds

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
> $subject
There can be situations where username is appended with the user store domain.
(Here we are assuming the request initiated user name and corresponding shared user name is same)
=> Remove domain from username when checking authorized organizations

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
> Cast timestamp to datetime before comparing in mssql to avoid possible infinite loop
We cover <, >, <=, >= method which include possible datetime columns in this PR. This is done only for mssql db because other db does not have this issue
=> Cast timestamps to datetime before compare in mssql

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java
Related to: https://github.com/wso2/product-is/issues/20700
> When getting organizations from the /organization GET API with an after or before pagination cursor, the returned lists of organizations are wrong if the local time zone of the system running the code to a different time zone than UTC.
```
namedPreparedStatement.setTimeStamp(entry.getKey(), Timestamp.valueOf(entry.getValue()), CALENDAR);
```
- Here a UTC Calendar instance is passed when setting the Timestamp value. 
- This approach takes the time string value provided (from entry.getValue()), which is already specified for the UTC zone, and converts it to UTC according to the local time zone.
- Therefore the Timestamp value changes according to the local system time zone, leading to incorrect pagination.
- This PR will revert …
=> Fixed wrong pagination results returned from the GET organizations DAO

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
> There is a rollback mechanism when org creation failure. But if the org deletion cause an exception the original issue which cause for the failure of the org creation flow will be not logged. Ideally, the published logs contains not the reason for org creation failure, but the reason for the failure of the rollback.
=> Improve exception handling when error occured during the rollback of organization creation failure

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
> $subject
Fixes https://github.com/wso2/product-is/issues/21203
=> Add new constants for removing application shared link

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
$Subject
This PR reverts the accidental removal of the ROOT_TENANT_DOMAIN from the PR: https://github.com/wso2/identity-organization-management-core/pull/144
=> Revert ROOT_TENANT_DOMAIN constant removal

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java, components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
The organization name can have any character as there is no specific regular expression defined to validate organization name. Due to that malicious organization names with HTML content can be created and those organization names will be shown in the email send for the user invitations etc..
Email templates can be updated with HTML content by the administrators also. But as we have the capability to validate the organization name with HTML content while creating and update organizations, its better to have a validation until proper organization name regular expression is defined.
=> Block organization name with HTML content

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
When the organization ID passed to resolve the tenant domain is null, it checks in cache. The cache key is based on organization ID which is derived by calling the hash code method. There is possibility of NPE at this place [1]
[1] - https://github.com/wso2/identity-organization-management-core/blob/main/components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/cache/OrganizationIdCacheKey.java#L62
We may able to improve the hash code generation logic to not to cause a NPE also.
Any how the service layer should have validation for such cases like not Empty checks.
=> Check for invalid organization IDs like empty string or null values passed to resolve tenant domain function

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java, components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/util/UtilsTest.java, components/org.wso2.carbon.identity.organization.management.service/src/test/resources/testng.xml
When the primary user store domain name is changed from `PRIMARY` to a different name, the invitation domain still returns `PRIMARY`. This results in sub-organizations being displayed in read-only mode, even for the user who created the organization. To address this issue, this PR introduces logic to dynamically resolve the primary domain name when it has been changed.
- https://github.com/wso2/product-is/issues/21348
=> Fix the issue with resolving invitation domain when the primary domain name is changed

.github/workflows/pr-builder.yml
$ Subject due to https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
=> Change actions/cache to v4

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
The purpose of this change is to introduce a new error code, `ERROR_CODE_UPDATE_ORGANIZATION_USER_ASSOCIATIONS`, which will be used to indicate failures when updating organization user associations.
- Introduce a specific error code to improve error handling and debugging for organization user association updates.
- Ensure consistency in error messages by following a structured format.
Added 
```
ERROR_CODE_UPDATE_ORGANIZATION_USER_ASSOCIATIONS("65143", "Unable to update organization user associations.", "Server encountered an error while updating organization user associations for the user.")
```
to `ErrorMessages` enum.
---
[Introduce Error Code for Organization User Association Update Failure #22983](https://github.com/wso2/product-is/issues/22983)
=> Add new error code for updating organization user associations

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java
The purpose of this change is to introduce a new error code, `ERROR_CODE_CHECK_ORGANIZATION_USER_ASSOCIATIONS`, which will be used to indicate failures when checking for organization user associations.
- Introduce a specific error code to improve error handling and debugging for organization user association checkings.
- Ensure consistency in error messages by following a structured format.
Added 
```
ERROR_CODE_ERROR_CHECK_ORGANIZATION_USER_ASSOCIATIONS("65144", "Unable to check if organization user associations exist.", "Server encountered an error while checking organization user associations for the user.")
```
to `ErrorMessages` enum.
---
[Introduce Error Code for Organization User Association Checking Failure #22990](https://github.com/wso2/product-is/issues/22990)
=> Add new error code for checking organization user associations

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java
Extend the database detection mechanism in Identity Organization Management Core by adding support for DB2 and PostgreSQL.
- Introduce constants for `DB2` and `POSTGRESQL` database types.
- Implement methods `isDB2DB()` and `isPostgreSqlDB()` to detect these databases.
- Ensure consistency with existing database detection logic.
- Defined `DB2` and `POSTGRESQL` as constants.
- Implemented `isDB2DB()` and `isPostgreSqlDB()` using the existing isDBTypeOf(String dbType) method.
- Maintained consistency with existing methods such as `isOracleDB()`, `isMSSqlDB()`, and `isMySqlDB()`.
- Ensured proper handling of database metadata checks to prevent errors during detection.
=> Add support for DB2 and PostgreSQL detection in Identity Organization Management Core

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/OrganizationManagementUtil.java, components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/util/OrganizationManagementUtilTest.java
$subject
This method provides the proper way to retrieve the Super Organization name. Please avoid using the hardcoded "SUPER" constant in implementations.
=> Add util method to fetch the super root organization name

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/test/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImplTest.java
Previously, `hasChildren` attribute in the BasicOrganization object was not populated from the `getBasicOrganizationDetailsByOrgIDs(List<String> orgIds)` DAO method.
That is due to missing this flow in the improvement we did through https://github.com/wso2/identity-organization-management-core/pull/190
This PR will add the neccessary query improvements to populate that value.
- https://github.com/wso2/product-is/issues/24843
=> Populate haschildren value in BasicOrganization object from getBasicOrganizationDetailsByOrgIDs() DAO method

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManager.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/util/Utils.java
Adds a new method `getOrganizationVersion` to obtain the version of an organization as defined in https://github.com/wso2/product-is/issues/24463.
- https://github.com/wso2/product-is/issues/24283
=> Add getOrganizationVersion method

components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/OrganizationManagerImpl.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/cache/OrganizationVersionCache.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/cache/OrganizationVersionCacheEntry.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/OrganizationManagementConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/constant/SQLConstants.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/OrganizationManagementDAO.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/CacheBackedOrganizationManagementDAO.java, components/org.wso2.carbon.identity.organization.management.service/src/main/java/org/wso2/carbon/identity/organization/management/service/dao/impl/OrganizationManagementDAOImpl.java, features/org.wso2.carbon.identity.organization.management.core.server.feature/resources/organization-mgt.xml, features/org.wso2.carbon.identity.organization.management.core.server.feature/resources/organization-mgt.xml.j2
This pull request introduces organization version caching to improve performance and consistency when retrieving organization version information. The main changes include adding cache classes for organization version, updating DAO implementations to use the cache, and modifying configuration files to enable and configure the new cache.
**Caching enhancements:**
* Added new classes `OrganizationVersionCache` and `OrganizationVersionCacheEntry` to store and manage organization version data in cache. 
* Updated `CacheBackedOrganizationManagementDAO` to utilize the organization version cache when retrieving organization version, and to clear the cache when organization data changes. 
**DAO and service layer changes:**
* Added a new method `getOrganizationVersion` to the …
=> Introduce organization version cache
